# Generated by ChatGPT migration scaffold

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("property_type", models.CharField(blank=True, max_length=64)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("size", models.PositiveIntegerField(blank=True, null=True)),
                ("bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bathrooms", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("year_built", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("rented", "Rented"), ("maintenance", "Maintenance")],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("lat", models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ("lng", models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=64)),
                ("lease_start_date", models.DateField(blank=True, null=True)),
                ("lease_end_date", models.DateField(blank=True, null=True)),
                ("monthly_rent", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "property",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenants",
                        to="core.property",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.CharField(max_length=40, primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("pending", "Pending"), ("overdue", "Overdue")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="core.property"),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="core.tenant"),
                ),
            ],
            options={"ordering": ["due_date", "id"]},
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.CharField(max_length=40, primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("generated_at", models.DateField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="core.payment"),
                ),
                (
                    "property",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="core.property"),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="core.tenant"),
                ),
            ],
            options={"ordering": ["issue_date", "id"]},
        ),
    ]
